### ISSUE TITLE
Sample script stops the page from loading and forces the page to become unresponsive

### ISSUE THREAD

**Issue by elbobo** [luiguild/aframe-svg-extruder#2] opened 2018-06-24 14:10 UTC
Hi, Great component, I am having problems getting it to work however. 

When I include this script;

`<script src="https://unpkg.com/aframe-svg-extruder@1.0.0/dist/index.min.js"></script>`

It stops the page from loading correctly (its just a blank white screen). If I can get to the inspector (which I cannot always) it seems to be causing problems as the body tag is empty. The page eventually becomes unresponsive and I have to kill it. 

I am trying to use it with the following spec 
A-frame `8.2` 
in Glitch Editor
Chrome browser (Version 67.0.3396.87 (Official Build) (64-bit)) on a Mac (10.11.16)

Please find a below a link that will allow you to edit the glitch project to see what I am experiencing.

https://glitch.com/edit/#!/join/7b61d922-97ae-48f4-b856-9afd6efefc39

As far as I can tell the script itself is the issue as commenting anything else out causes the same issues, only removing the script solves the problem.

Am I doing something wrong? Is this a glitch issue? Do I have to export the SVG at a particular spec?

Thanks for any advice, please let me know if you need any more info.

**Comment by luiguild** [comment] 2018-06-24 14:48
Hi @elbobo! Thanks to open the issue and try use a-svg!

Seened your glitch I noticed that the problem is in the SVG file that you want use. I don't know yet what the problem exactly, but I'll investigate. I edited your code and put other SVG file and worked fine.

I released another version of a-svg recently, it's no more 1.0.0, now its 1.0.2 (sorry for not update the readme I'll do it now).

If you could help me to investigate this problem I would greatly appreciate it.

I will close this for now.

Thanks!

**Closed as completed by luiguild** 2018-06-24 14:48 UTC

**Comment by elbobo** [comment] 2018-06-24 21:28
Hi @luiguild Thanks for getting back to me. Yes, your svg does seem to work so the problem was my file.

How can I help you to investigate? That svg file was generated by illustrator, I can try different export settings if you'd like and see if I have more luck?

Let me know how best to help out, thanks again
